name: Self Test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: self-test
        name: Invoke action
        uses: ./
        with:
          changelog-file: test/CHANGELOG.md
          version: 1.0.0
      - name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.self-test.outputs) }}
        run: |
          echo "${OUTPUTS}"
      - name: Check outputs
        run: |
          if test "${{ steps.self-test.outputs.changelog-file }}" != "test/CHANGELOG.md"; then
            echo "Expected changelog-file to be 'test/CHANGELOG.md', but got '${{ steps.self-test.outputs.changelog-file }}'."
            exit 1
          fi
