name: Self Test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Invoke action
        uses: ./
        with:
          changelog-file: test/CHANGELOG.md
          version: 1.0.0
